version: '3.8'

services:
  enet_api:
    build:
      context: ./01_api/
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./01_api/.env
    volumes:
      - ./01_api/app/data:/app/data
  streamlit:
    build:
      context: ./02_stresmlit/
    restart: always
    ports:
      - "8001: 8001"